Repository proDreams/taiga_wh_notifier, pull requests merged in 2025-03, with the labels that each got.

#56 refactor(logger_utils.py): improved log message format
  src/utils/logger_utils.py
  tests/configuration/test_logger_class.py
Labels: refactor

#57 ashikhmin/task_184
  src/core/app.py
  src/core/settings.py
  src/entities/schemas/user_data/user_schemas.py
  src/infrastructure/broker/redis_dependency.py
  src/infrastructure/database/mongo_dependency.py
  src/logic/bot_logic/filters/menu_command_filter.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/dynamic_profile_keyboards.py
  src/logic/bot_logic/keyboards/dynamic_projects_keyboards.py
  src/logic/bot_logic/keyboards/keyboard_generator.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/services/project_service.py
  src/logic/services/user_service.py
  src/runner.py
  src/utils/send_message_utils.py
  src/utils/state_utils.py
  src/utils/text_utils.py
  src/utils/yaml_utils.py
  tests/configuration/test_logger_class.py
  tests/configuration/test_yaml_utils.py
Labels: refactor

#59 vangeli/task_186
  src/entities/callback_classes/__init__.py
  src/entities/callback_classes/profile_callbacks.py
  src/entities/schemas/profile_data/__init__.py
  src/entities/schemas/profile_data/language_schema.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/services/profile_service.py
  src/utils/text_utils.py
  strings/dynamic_keyboards.yaml
  strings/keyboard_buttons.yaml
  strings/static_keyboards.yaml
Labels: feat, refactor

#60 feat: add crud to change language
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  strings/keyboard_text.yaml
Labels: feat

#61 ashikhmin/task_194_195
  README-RU.md
  README.md
  src/core/settings.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/services/profile_service.py
Labels: docs, fix

#62 fix: update pydantic schemas
  src/entities/schemas/webhook_data/base_webhook_schemas.py
  src/entities/schemas/webhook_data/nested_schemas.py
  tests/entities/fixtures/expected_user_story.txt
  tests/entities/test_webhook_payload_schemas.py
Labels: fix

#63 Vangeli/issue 205
  src/entities/schemas/webhook_data/base_webhook_schemas.py
  src/entities/schemas/webhook_data/diff_webhook_schemas.py
  src/entities/schemas/webhook_data/nested_schemas.py
  src/entities/schemas/webhook_data/webhook_payload_schemas.py
Labels: fix, refactor

#64 Korolev/task 179
  src/entities/callback_classes/__init__.py
  src/entities/callback_classes/project_callbacks.py
  src/entities/schemas/project_data/project_schemas.py
  src/entities/states/project_states.py
  src/infrastructure/database/mongo_manager.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/services/project_service.py
  strings/keyboard_buttons.yaml
  strings/static_keyboards.yaml
  tests/infrastructure/database/test_mongo_manager.py
Labels: feat

#51 pre version msg_formatter
  .gitignore
  config/settings.yaml.example
  src/entities/enums/event_enums.py
  src/utils/msg_formatter_utils.py
  strings/message_schema.yaml
  strings/messages_text.yaml
  strings/webhook_notifications.yaml
  tests/entities/fixtures/test.json
Labels: feat

#65 ashikhmin/tasks_138_215
  .github/workflows/pull_request_merge_notify.yaml
  Makefile
  README-RU.md
  README.md
  config/settings.yaml.example
  src/core/app.py
  src/entities/callback_classes/__init__.py
  src/logic/bot_logic/handlers/__init__.py
  src/logic/bot_logic/handlers/service_handlers/__init__.py
  src/logic/bot_logic/handlers/service_handlers/service_errors_handler.py
  src/logic/bot_logic/handlers/service_handlers/service_events_handlers.py
  src/utils/text_utils.py
  strings/service_text.yaml
Labels: docs, feat, refactor, ci/cd

#69 ci/cd: fix PR notify workflow
  .github/workflows/pull_request_merge_notify.yaml
Labels: ci/cd

#72 ashikhmin/task_187
  src/entities/callback_classes/pagination_callbacks.py
  src/entities/callback_classes/project_callbacks.py
  src/entities/enums/edit_action_type_enum.py
  src/entities/enums/profile_action_type_enum.py
  src/entities/states/active_state.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/services/user_service.py
  strings/messages_text.yaml
  strings/static_keyboards.yaml
Labels: fix, refactor

#74 ashikhmin/task_86_2
  src/core/app.py
  src/entities/schemas/project_data/project_types_schemas.py
  src/logic/bot_logic/handlers/service_handlers/service_errors_handler.py
  src/logic/services/profile_service.py
  src/logic/services/webhook_service.py
  src/logic/web_app_logic/exception_handler.py
  src/logic/web_app_logic/route_dependency/route_path_validator.py
  src/presentation/web_app_routes/webhook_route.py
  src/utils/msg_formatter_utils.py
  src/utils/text_utils.py
Labels: feat, fix, refactor

#76 refactor: update messages text and buttons text
  strings/keyboard_text.yaml
  strings/keyboards_buttons.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
Labels: refactor

#81 ashikhmin/readme_and_compose
  README-RU.md
  README.md
  caddy/Caddyfile
Labels: docs

#86 Ashikhmin/update pr workflow
  .github/workflows/pull_request_merge_notify.yaml
Labels: ci/cd

#89 fix: issue #238
  src/core/app.py
  src/infrastructure/database/mongo_manager.py
  src/logic/services/project_service.py
Labels: fix

#91 fix: issue #242
  config/settings.example.yaml
  config/settings.prod_example.yaml
  src/entities/schemas/webhook_data/base_webhook_schemas.py
  src/entities/schemas/webhook_data/diff_webhook_schemas.py
  src/entities/schemas/webhook_data/nested_schemas.py
  src/entities/schemas/webhook_data/webhook_payload_schemas.py
Labels: fix

#93 feat: improved chat ID format instructions in `messages_text.yaml`
  strings/messages_text.yaml
Labels: refactor

#95 vangeli/task_244-246
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/utils/validated_text.py
  strings/messages_text.yaml
Labels: fix

#92 refactor: add settings validators and clean file from optional values
  README-RU.md
  README.md
  config/settings.prod_example.yaml
  docker-compose.caddy.yaml
  docker-compose.yaml
  src/core/settings.py
Labels: refactor

#97 Ashikhmin/fix text file
  strings/lang/ru/keyboard_text.yaml
  strings/messages_text.yaml
Labels: fix

#100 vangeli/task_245-246_fix
  src/utils/validated_text.py
  strings/lang/ru/messages_text.yaml
Labels: fix
