Repository proDreams/taiga_wh_notifier, pull requests merged in 2025-02, with the labels that each got.

#1 Ashikhmin/task 34
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
Labels: enhancement

#2 ashikhmin/task_30_33
  .env.example
  .gitignore
  docker-compose.dev.yaml
  pyproject.toml
  uv.lock
Labels: enhancement

#3 fix: update port mapping in development environment
  docker-compose.dev.yaml
Labels: fix

#5 feat: added example settings configuration and updated gitignore
  .gitignore
  config/settings.yaml.example
Labels: feat

#8 refactor: update notify fields in lint workflow
  .github/workflows/lint.yaml
Labels: refactor

#9 ashikhmin/task_59
  pyproject.toml
  src/core/Base/__init__.py
  src/core/Base/singleton.py
  src/core/settings.py
  tests/__init__.py
  tests/configuration/__init__.py
  tests/configuration/test_configuration_class.py
  uv.lock
Labels: feat

#10 feat: added runner script and build configuration
  pyproject.toml
  src/runner.py
  uv.lock
Labels: feat

#11 fix: update README and markdown files for consistent style
  .github/CONTRIBUTING-RU.md
  .github/CONTRIBUTING.md
  .github/STYLEGUIDE-RU.md
  .github/STYLEGUIDE.md
  README-RU.md
  README.md
Labels: docs

#12 fix: `LEVEL` -> `LOG_LEVEL`, `MAX_SIZE` -> `MAX_SIZE_MB` and update value
  config/settings.yaml.example
Labels: fix

#6 feat: add module `yaml_utils` with function `read_file`
  config/settings.yaml.example
  src/core/settings.py
  src/utils/yaml_utils.py
  tests/configuration/fixtures/strings/yaml_test.yaml
  tests/configuration/test_yaml_utils.py
  tests/tests/configuration/fixtures/logs/logs.txt
Labels: feat

#13 fix: remove `test.py` from root
  test.py
Labels: fix

#14 Ashikhmin/task 63
  .github/workflows/lint_and_test.yaml
  tests/configuration/test_yaml_utils.py
Labels: ci/cd

#15 fix: add `logs.txt` to `.gitignore`
  .gitignore
Labels: fix

#16 ashikhmin/task_66
  .github/images/logo.png
  README-RU.md
  README.md
Labels: docs

#17 feat: added sections for development and design credits in README files
  README-RU.md
  README.md
Labels: docs

#18 ashikhmin/task_75
  config/settings.yaml.example
  src/core/app.py
  src/core/settings.py
  src/entities/enums/__init__.py
  src/entities/enums/environment_enum.py
  src/runner.py
  tests/configuration/test_configuration_class.py
  tests/configuration/test_yaml_utils.py
Labels: feat

#20 fix: update pytest command to include environment variables
  .github/workflows/lint_and_test.yaml
Labels: fix, ci/cd

#21 vangeli/task_68
  src/core/app.py
  src/core/settings.py
  src/logic/bot_logic/handlers/__init__.py
  src/logic/bot_logic/handlers/admins_handlers/__init__.py
  src/logic/bot_logic/handlers/commons_handlers/__init__.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/__init__.py
  src/logic/bot_logic/keyboards/__init__.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/bot_logic/keyboards/keyboards_stash.py
  src/presentation/__init__.py
  src/presentation/bot_routers/__init__.py
  src/presentation/bot_routers/init_router.py
  src/utils/yaml_utils.py
  strings/keyboards_buttons.yaml
  strings/messages_text.yaml
  tests/configuration/fixtures/strings/keyboards_buttons.yaml
  tests/configuration/test_keyboard_model.py
Labels: feat, fix

#22 ashikhmin/fix_init_bot_rourers
  src/core/app.py
  src/presentation/bot_routers/init_router.py
Labels: fix

#23 Ashikhmin/task 107
  .github/workflows/lint_and_test.yaml
  config/settings.yaml.example
  pyproject.toml
  pytest.ini
  src/entities/enums/environment_enum.py
  src/infrastructure/broker/redis_dependency.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/utils/yaml_utils.py
  tests/infrastructure/__init__.py
  tests/infrastructure/broker/__init__.py
  tests/infrastructure/broker/test_redis_dependency.py
  uv.lock
Labels: docs, feat, ci/cd

#25 ashikhmin/task_112
  config/settings.yaml.example
  src/infrastructure/broker/redis_dependency.py
  src/infrastructure/database/mongo_dependency.py
  tests/infrastructure/database/__init__.py
  tests/infrastructure/database/test_database_dependency.py
Labels: feat

#26 vangeli/task_87
  src/entities/schemas/webhook_data/__init__.py
  src/entities/schemas/webhook_data/base_schemas.py
  src/entities/schemas/webhook_data/nested_schemas.py
  src/entities/schemas/webhook_data/webhook_payload_schemas.py
  tests/entities/__init__.py
  tests/entities/fixtures/__init__.py
  tests/entities/fixtures/expected_milestone.txt
  tests/entities/fixtures/expected_task.txt
  tests/entities/fixtures/expected_user_story.txt
  tests/entities/fixtures/milestone_raw.json
  tests/entities/fixtures/task_raw.json
  tests/entities/fixtures/user_story_raw.json
  tests/entities/test_webhook_payload_schemas.py
Labels: feat

#27 fix: test to pydantic schemas to webhook payload
  tests/entities/fixtures/expected_milestone.txt
  tests/entities/fixtures/expected_task.txt
  tests/entities/fixtures/expected_user_story.txt
  tests/entities/fixtures/milestone_raw.json
  tests/entities/fixtures/task_raw.json
  tests/entities/fixtures/user_story_raw.json
Labels: fix

#28 ashikhmin/task_113
  src/infrastructure/broker/redis_manager.py
  tests/infrastructure/broker/test_redis_manager.py
Labels: feat

#29 vangeli/task_103
  .gitignore
  config/settings.yaml.example
  src/core/settings.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/bot_logic/keyboards/keyboards_stash.py
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
  tests/configuration/fixtures/strings/keyboards_buttons.yaml
  tests/configuration/test_keyboard_model.py
  tests/fixtures/logs/logs.txt
  tests/fixtures/strings/keyboards_buttons.yaml
  tests/fixtures/strings/keyboards_language.yaml
  tests/fixtures/strings/keyboards_list.yaml
  tests/fixtures/strings/yaml_test.yaml
  tests/logic/__init__.py
  tests/logic/bot_logic/__init__.py
  tests/logic/bot_logic/keyboards/__init__.py
  tests/logic/bot_logic/keyboards/test_keyboard_model.py
Labels: feat, fix

#30 fix: fix keyboards yaml source files
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
  tests/fixtures/strings/keyboards_buttons.yaml
  tests/fixtures/strings/keyboards_language.yaml
  tests/fixtures/strings/keyboards_list.yaml
Labels: fix

#33 ashikhmin/task_84
  src/core/app.py
  src/entities/enums/collection_enum.py
  src/entities/enums/event_enums.py
  src/entities/schemas/base_data/__init__.py
  src/entities/schemas/base_data/base_schemas.py
  src/entities/schemas/project_data/__init__.py
  src/entities/schemas/project_data/base_project_schemas.py
  src/entities/schemas/project_data/project_schemas.py
  src/entities/schemas/project_data/project_types_schemas.py
  src/entities/schemas/validators/__init__.py
  src/entities/schemas/validators/project_validators.py
  src/entities/schemas/webhook_data/base_webhook_schemas.py
  src/entities/schemas/webhook_data/nested_schemas.py
  src/entities/schemas/webhook_data/webhook_payload_schemas.py
  src/infrastructure/database/mongo_dependency.py
  src/infrastructure/database/mongo_manager.py
  src/logic/web_app_logic/route_dependency/__init__.py
  src/logic/web_app_logic/route_dependency/route_path_validator.py
  src/presentation/web_app_routes/__init__.py
  src/presentation/web_app_routes/webhook_route.py
  tests/entities/test_objectid_validation.py
  tests/infrastructure/database/test_mongo_manager.py
  tests/presentation/__init__.py
  tests/presentation/web_app_routes/__init__.py
  tests/presentation/web_app_routes/test_webhook_route.py
Labels: feat

#34 feat: added update router for handling bot updates
  src/presentation/web_app_routes/__init__.py
  src/presentation/web_app_routes/update_router.py
Labels: feat

#35 ashikhmin/task_91
  src/core/Base/exceptions.py
  src/utils/send_message_utils.py
  tests/utils/__init__.py
  tests/utils/test_send_message_utils.py
Labels: feat

#36 vangeli/task_93
  .pre-commit-config.yaml
  src/entities/callback_classes/AdminActions.py
  src/entities/callback_classes/EditProject.py
  src/entities/callback_classes/Pagination.py
  src/entities/callback_classes/__init__.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/edit_action_type_enum.py
  src/logic/bot_logic/handlers/__init__.py
  src/logic/bot_logic/handlers/admins_handlers/__init__.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/__init__.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/__init__.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
Labels: feat, fix

#37 ashikhmin/task_131
  config/settings.yaml.example
  src/core/app.py
  src/entities/schemas/base_data/base_schemas.py
  src/entities/schemas/project_data/base_project_schemas.py
  src/entities/schemas/project_data/project_schemas.py
  src/entities/schemas/project_data/project_types_schemas.py
  src/entities/schemas/user_data/__init__.py
  src/entities/schemas/user_data/user_schemas.py
  src/infrastructure/database/mongo_dependency.py
  src/infrastructure/database/mongo_manager.py
  src/logic/bot_logic/middlewares/__init__.py
  src/logic/bot_logic/middlewares/user_middleware.py
  src/logic/services/__init__.py
  src/logic/services/user_service.py
  src/logic/web_app_logic/route_dependency/mongo_dependency.py
  src/logic/web_app_logic/route_dependency/route_path_validator.py
  src/presentation/bot_routers/init_router.py
  src/presentation/web_app_routes/__init__.py
  src/presentation/web_app_routes/update_route.py
  tests/entities/test_objectid_validation.py
Labels: docs, feat, fix

#39 vangeli/task_146
  src/entities/callback_classes/Instructions.py
  src/logic/bot_logic/handlers/__init__.py
  src/logic/bot_logic/handlers/instructions_handlers/__init__.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
Labels: feat, fix

#40 vangeli/task_141
  src/entities/callback_classes/EditProject.py
  src/entities/enums/edit_action_type_enum.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  strings/keyboards_buttons.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
Labels: feat, fix, refactor

#41 fix: change handler name
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
Labels: fix

#42 vangeli/task_151
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/utils/text_utils.py
  strings/messages_text.yaml
Labels: fix, refactor

#44 vangeli/task_154
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/profile_keyboards.py
  strings/keyboards_list.yaml
Labels: feat

#46 vangeli/task_156
  src/entities/callback_classes/AdminActions.py
  src/entities/callback_classes/EditProject.py
  src/entities/callback_classes/ProfileMenu.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/edit_action_type_enum.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
Labels: feat, refactor

#47 ashikhmin/task_152
  src/entities/callback_classes/admin_callbacks.py
  src/entities/callback_classes/instruction_callbacks.py
  src/entities/callback_classes/pagination_callbacks.py
  src/entities/callback_classes/profile_callbacks.py
  src/entities/callback_classes/project_callbacks.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/edit_action_type_enum.py
  src/entities/enums/lang_enum.py
  src/entities/enums/profile_action_type_enum.py
  src/entities/schemas/user_data/user_schemas.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/instructions_handlers/instructions_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/bot_logic/keyboards/profile_keyboards.py
  src/logic/bot_logic/middlewares/user_middleware.py
Labels: feat, fix

#49 ashikhmin/task_160
  src/core/app.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/collection_enum.py
  src/entities/enums/edit_action_type_enum.py
  src/entities/enums/environment_enum.py
  src/entities/enums/event_enums.py
  src/entities/enums/lang_enum.py
  src/entities/enums/profile_action_type_enum.py
  src/infrastructure/database/mongo_manager.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/profile_keyboards.py
  src/logic/services/project_service.py
  src/logic/services/user_service.py
  src/logic/web_app_logic/route_dependency/route_path_validator.py
  tests/infrastructure/database/test_mongo_manager.py
Labels: feat, fix, refactor

#52 refactor: corrected enums field in admin handlers
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
Labels: refactor

#53 vangeli/task_161
  src/entities/callback_classes/admin_callbacks.py
  src/entities/callback_classes/instruction_callbacks.py
  src/entities/callback_classes/profile_callbacks.py
  src/entities/callback_classes/project_callbacks.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/edit_action_type_enum.py
  src/entities/enums/profile_action_type_enum.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/dynamic_admins_keyboards.py
  src/logic/bot_logic/keyboards/dynamic_profile_keyboards.py
  src/logic/bot_logic/keyboards/dynamic_projects_keyboards.py
  src/logic/bot_logic/keyboards/keyboard_model.py
  src/logic/bot_logic/keyboards/profile_keyboards.py
  src/utils/text_utils.py
  strings/keyboards_buttons.yaml
  strings/keyboards_language.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
  tests/logic/bot_logic/keyboards/test_keyboard_model.py
Labels: feat, fix, refactor

#54 Ashikhmin/keyboard rework
  .pre-commit-config.yaml
  pyproject.toml
  src/core/Base/exceptions.py
  src/core/settings.py
  src/entities/callback_classes/__init__.py
  src/entities/callback_classes/admin_callbacks.py
  src/entities/callback_classes/menu_callbacks.py
  src/entities/callback_classes/profile_callbacks.py
  src/entities/callback_classes/project_callbacks.py
  src/entities/enums/admin_action_type_enum.py
  src/entities/enums/collection_enum.py
  src/entities/enums/event_enums.py
  src/entities/enums/handlers_enum.py
  src/entities/enums/keyboard_enum.py
  src/entities/schemas/user_data/user_schemas.py
  src/entities/states/admin_states.py
  src/infrastructure/broker/redis_dependency.py
  src/infrastructure/database/mongo_manager.py
  src/logic/bot_logic/filters/__init__.py
  src/logic/bot_logic/filters/menu_command_filter.py
  src/logic/bot_logic/handlers/admins_handlers/admins_handlers.py
  src/logic/bot_logic/handlers/commons_handlers/commands_handlers.py
  src/logic/bot_logic/handlers/profile_handlers/profile_handlers.py
  src/logic/bot_logic/handlers/projects_handlers/projects_handlers.py
  src/logic/bot_logic/keyboards/dynamic_admins_keyboards.py
  src/logic/bot_logic/keyboards/keyboard_generator.py
  src/logic/bot_logic/middlewares/dependency_middleware.py
  src/logic/bot_logic/middlewares/user_middleware.py
  src/logic/services/user_service.py
  src/presentation/bot_routers/init_router.py
  src/utils/send_message_utils.py
  src/utils/text_utils.py
  src/utils/yaml_utils.py
  strings/dynamic_keyboards.yaml
  strings/keyboard_buttons.yaml
  strings/keyboard_text.yaml
  strings/keyboards_list.yaml
  strings/messages_text.yaml
  strings/static_keyboards.yaml
  tests/fixtures/strings/keyboard_buttons.yaml
  tests/fixtures/strings/keyboard_text.yaml
  tests/fixtures/strings/static_keyboards.yaml
  tests/logic/bot_logic/keyboards/test_keyboard_model.py
  uv.lock
Labels: docs, feat, fix, refactor
